using System.Collections.Generic;
using HyoutaUtils;

namespace HyoutaTools.Tales.Graces.TranslationPort {
	internal static partial class Mappings {
		private static void GetFileMappingsRoot(FileFetcher _fc, Dictionary<string, MappingData> files) {
			files.Add(@"rootR.cpk/btl/acf/bin000.acf", new MappingData(c: true, w: new W().Sys(0).Sys(13).R(33, 33).Un(259).Un(260)));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC001.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC002.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC003.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC004.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC005.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC006.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC007.scs", new MappingData(c: true, u: new M().Merge(15, 16, "\n")));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC008.scs", new MappingData(c: true, u: new M().Merge(24, 25, "\n")));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC009.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC010.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC011.scs", new MappingData(c: true, j: new M().A(33, -2), u: new M().Merge(15, 16, "\n")));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC012.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC013.scs", new MappingData(c: true, j: new M().A(23, 20)));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC014.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC015.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC016.scs", new MappingData(c: true, u: new M().Merge(18, 19, "\n")));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC017.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC018.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC019.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC020.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC021.scs", new MappingData(c: true, u: new M().Merge(17, 18, "\n")));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC022.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC023.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC024.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC025.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC026.scs", new MappingData(c: true, u: new M().Merge(19, 20, "\n")));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC027.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC028.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC029.scs", new MappingData(c: true, u: new M().Merge(18, 19, "\n")));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC030.scs", new MappingData(c: true, j: new M().A(20, 14).A(29, 28, 28, 28, 28)));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC031.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC032.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC033.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC034.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC035.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC036.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC037.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC038.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC039.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC040.scs", new MappingData(c: true, j: new M().A(20, 17)));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC041.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC042.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC043.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC044.scs", new MappingData(c: true, j: new M().A(28, 15)));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC045.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC046.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC047.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC048.scs", new MappingData(c: true, j: new M().A(32, 31)));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC049.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC050.scs", new MappingData(c: true, j: new M().A(22, 21)));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC051.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC052.scs", new MappingData(c: true, j: new M().A(19, 18)));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC053.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC054.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC055.scs", new MappingData(c: true, u: new M().Merge(16, 17, "\n")));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC056.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC057.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC058.scs", new MappingData(c: true, u: new M().Merge(30, 31, "\n")));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC059.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC060.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC061.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC062.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC063.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC064.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC065.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC066.scs", new MappingData(c: true, j: new M().A(26, 25)));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC067.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC068.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC069.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC070.scs", new MappingData(c: true, u: new M().Merge(19, 20, "\n")));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC071.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC072.scs", new MappingData(c: true, u: new M().Merge(20, 21, "\n")));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC073.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC074.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC075.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC076.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DC077.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DL001.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DL002.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DL003.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DL004.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DL005.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DL006.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DL007.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DL008.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DL009.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DL010.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DL011.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DL012.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DL013.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DL014.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DL016.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DL017.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DL018.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DL019.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_DL021.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS001.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS002.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS003.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS004.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS005.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS006.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS007.scs", new MappingData(c: true, u: new M().Merge(19, 20, "\n", new List<int>() { 0, 2, 3 }, new List<int>() { 152 })));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS008.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS009.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS010.scs", new MappingData(c: true, j: new M().A(21, 13), multiplyOutSkit: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS011.scs", new MappingData(c: true, j: new M().A(19, 13).A(20, 13), multiplyOutSkit: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS012.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS013.scs", new MappingData(c: true, u: new M().Merge(15, 16, "\n", new List<int>() { 0, 2, 3 }, new List<int>() { 126 })));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS014.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS015.scs", new MappingData(c: true, j: new M().A(20, 19, 19)));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS016.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS017.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS018.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS019.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS020.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS021.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS022.scs", new MappingData(c: true, u: new M().Merge(16, 17, "\n", new List<int>() { 0, 1, 3 }, new List<int>() { 57 })));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS023.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS024.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS025.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS026.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS027.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS028.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS029.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS030.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS031.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS032.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS033.scs", new MappingData(c: true, u: new M().Merge(19, 20, "\n", new List<int>() { 2 })));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS034.scs", new MappingData(c: true, u: new M().Merge(17, 18, "\n")));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS035.scs", new MappingData(c: true, u: new M().Merge(16, 17, "\n", new List<int>() { 1, 2 }, new List<int>() { 110 })));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS036.scs", new MappingData(c: true, u: new M().Merge(16, 17, "\n", new List<int>() { 0, 2 })));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS037.scs", new MappingData(c: true, u: new M().Merge(24, 25, "\n", new List<int>() { 2 })));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS038.scs", new MappingData(c: true, u: new M().Merge(14, 15, "\n", new List<int>() { 0, 1, 2 }, new List<int>() { 54, 100 })));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS039.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS040.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS041.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS042.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS043.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS044.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS045.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS046.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS047.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS048.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS049.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS050.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS051.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS052.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS053.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS054.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS055.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS056.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS057.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS058.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS059.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS060.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS061.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS062.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS063.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS064.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS065.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS066.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS067.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS068.scs", new MappingData(c: true, u: new M().Merge(19, 20, "\n", new List<int>() { 0, 1, 2 }, new List<int>() { 69, 140 }).Merge(22, 23, "\n", new List<int>() { 0, 1, 2 }, new List<int>() { 70, 140 })));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS069.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS070.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS071.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS072.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS073.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS074.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS075.scs", new MappingData(c: true, u: new M().Merge(18, 19, "\n", new List<int>() { 0 })));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS076.scs", new MappingData(c: true, u: new M().Merge(13, 14, "\n", new List<int>() { 0, 1, 2 }, new List<int>() { 55, 121 }), w: new W().P(17, (o, r) => r.RemoveMultispace())));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS077.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS078.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS079.scs", new MappingData(c: true, u: new M().Merge(17, 18, "\n", new List<int>() { 0, 2, 4 })));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS080.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS081.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS082.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS083.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS084.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS085.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS086.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS087.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS088.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS089.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS090.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS091.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS092.scs", new MappingData(c: true, u: new M().Merge(18, 19, "\n", new List<int>() { 0, 1, 2 }, new List<int>() { 62 })));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS093.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS094.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS095.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS096.scs", new MappingData(c: true, j: new M().A(21, 13), u: new M().Merge(17, 18, "\n", new List<int>() { 0, 2 })));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS097.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS098.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS099.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS100.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS101.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS102.scs", new MappingData(c: true, u: new M().Merge(20, 21, "\n", new List<int>() { 2 })));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS103.scs", new MappingData(c: true, j: new M().A(20, 13)));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS104.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS105.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS106.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS107.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS108.scs", new MappingData(c: true, u: new M().Merge(18, 19, "\n", new List<int>() { 0, 2, 3 }, new List<int>() { 137 })));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS109.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS110.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS111.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS112.scs", new MappingData(c: true, u: new M().Merge(17, 18, "\n")));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS113.scs", new MappingData(c: true, u: new M().Merge(19, 20, "\n", new List<int>() { 0, 2 })));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS114.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS115.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS116.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS117.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS118.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS119.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS120.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS121.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS122.scs", new MappingData(c: true, j: new M().A(31, 27).A(37, 17), multiplyOutSkit: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS123.scs", new MappingData(c: true, j: new M().A(20, 14), multiplyOutSkit: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS124.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS125.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS126.scs", new MappingData(c: true, u: new M().Merge(19, 20, "\n", new List<int>() { 0, 1, 2 }, new List<int>() { 55, 114 })));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS127.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS128.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS129.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS130.scs", new MappingData(c: true, j: new M().A(23, 15), multiplyOutSkit: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS131.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS132.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS133.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS134.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS135.scs", new MappingData(c: true, u: new M().Merge(20, 21, "\n", new List<int>() { 0, 1, 3 }, new List<int>() { 54 })));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS136.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS137.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS138.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS139.scs", new MappingData(c: true, u: new M().Merge(17, 18, 19, "\n", new List<int>() { 0, 2, 3, 4, 5 }, new List<int>() { 156, 235 })));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS140.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS141.scs", new MappingData(c: true, j: new M().A(16, 15)));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS142.scs", new MappingData(c: true, u: new M().Merge(21, 22, "\n", new List<int>() { 0, 1 }, new List<int>() { 56 })));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS143.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS144.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS145.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS146.scs", new MappingData(c: true, u: new M().Merge(16, 17, "\n", new List<int>() { 0, 1, 2 }, new List<int>() { 54, 110 })));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS147.scs", new MappingData(c: true, j: new M().A(26, 25)));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS148.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS149.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS150.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS151.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS152.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS153.scs", new MappingData(c: true, u: new M().Merge(21, 22, "\n", new List<int>() { 0, 1, 2, 3 }, new List<int>() { 75, 148 })));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS154.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS155.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS156.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS157.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS158.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS159.scs", new MappingData(c: true, u: new M().Merge(19, 20, "\n", new List<int>() { 0, 1, 3 }, new List<int>() { 63 })));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS160.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS161.scs", new MappingData(c: true, u: new M().Merge(13, 14, "\n", new List<int>() { 0, 2 }, new List<int>() { 115 }), w: new W().R(17, 20)));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS162.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS163.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS164.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS165.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS166.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS167.scs", new MappingData(c: true, u: new M().Merge(20, 21, "\n", new List<int>() { 0, 2 }, new List<int>() { 122 })));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS168.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS169.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS170.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS171.scs", new MappingData(c: true, u: new M().Merge(14, 15, "\n", new List<int>() { 0, 1, 2 }, new List<int>() { 56, 115 })));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS172.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS173.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS174.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS175.scs", new MappingData(c: true, u: new M().Merge(14, 15, "\n", new List<int>() { 0 }).Merge(17, 18, 19, "\n", new List<int>() { 0, 1, 2, 3, 4 }, new List<int>() { 73, 150 })));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS176.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS177.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS178.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS179.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS180.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS181.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS182.scs", new MappingData(c: true, u: new M().Merge(16, 17, "\n", new List<int>() { 0, 1 }, new List<int>() { 60 })));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS183.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS184.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS185.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS186.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS187.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS188.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS189.scs", new MappingData(c: true, u: new M().Merge(15, 16, "\n")));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS190.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS191.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS192.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS193.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS194.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS195.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS196.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS197.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS198.scs", new MappingData(c: true, u: new M().Merge(23, 24, "\n", new List<int>() { 0, 1, 3 }, new List<int>() { 50 })));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS199.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS200.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS201.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS202.scs", new MappingData(c: true, u: new M().Merge(18, 19, "\n", new List<int>() { 0, 1, 2 }, new List<int>() { 72, 143 })));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS203.scs", new MappingData(c: true, u: new M().Merge(18, 19, "\n", new List<int>() { 0, 1, 2 }, new List<int>() { 79 })));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS204.scs", new MappingData(c: true, u: new M().Merge(18, 19, "\n").Merge(21, 22, "\n", new List<int>() { 1, 2 }, new List<int>() { 115 })));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS205.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS206.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS207.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS208.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS209.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS210.scs", new MappingData(c: true, u: new M().Merge(17, 18, "\n", new List<int>() { 0 }).Merge(23, 24, "\n", new List<int>() { 0, 2, 3 }, new List<int>() { 142 })));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS211.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS212.scs", new MappingData(c: true, u: new M().Merge(18, 19, "\n", new List<int>() { 0, 2, 3 }, new List<int>() { 145 })));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS213.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS214.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS215.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS216.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS217.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS218.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS219.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS220.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS221.scs", new MappingData(c: true, u: new M().Merge(19, 20, "\n", new List<int>() { 0, 2 }, new List<int>() { 109 })));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS222.scs", new MappingData(c: true, u: new M().Merge(16, 17, "\n", new List<int>() { 0, 2 })));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS223.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS224.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS225.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS226.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS227.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS228.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS229.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS230.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS231.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS232.scs", new MappingData(c: true, u: new M().Merge(17, 18, "\n", new List<int>() { 1, 2 }, new List<int>() { 108 })));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS233.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS234.scs", new MappingData(c: true, u: new M().Merge(20, 21, 22, "\n", new List<int>() { 0, 1, 2, 3, 4 }, new List<int>() { 73, 150, 226 })));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS235.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS236.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS237.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS238.scs", new MappingData(c: true, u: new M().Merge(31, 32, "\n", new List<int>() { 1, 2 }, new List<int>() { 109 }).A(35, -1), w: new W().Sys(32)));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS239.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS240.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS241.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_MS242.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_PR001.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_PR002.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_PR003.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_PR004.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_PR005.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_PR006.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_PR007.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB001.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB002.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB003.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB004.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB005.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB006.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB007.scs", new MappingData(c: true, j: new M().A(26, 25, 25, 25, 25)));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB008.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB009.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB010.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB011.scs", new MappingData(c: true, j: new M().A(20, -1)));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB012.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB013.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB014.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB015.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB016.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB017.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB018.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB019.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB020.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB021.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB022.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB023.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB024.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB025.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB026.scs", new MappingData(c: true, j: new M().A(17, -1).A(24, -2)));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB027.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB028.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB029.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB030.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB031.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB032.scs", new MappingData(c: true, j: new M().A(18, 17).A(25, 24, 24).A(27, 26, 26)));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB033.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB034.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB035.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB036.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB037.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB038.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB039.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB040.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB041.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB042.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB043.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB044.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB045.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB046.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB047.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB048.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB049.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB050.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB051.scs", new MappingData(c: true, j: new M().A(13, -1)));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB052.scs", new MappingData(c: true, u: new M().Merge(21, 22, 23, "\n", new List<int>() { 0, 1, 2, 3, 4 }, new List<int>() { 73, 145 })));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB053.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB054.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB055.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB056.scs", new MappingData(c: true, u: new M().Merge(18, 19, "\n")));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB057.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB058.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB059.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB060.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB061.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB062.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB063.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB064.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB065.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB066.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB067.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB068.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB069.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB070.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB071.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/CHT_SB072.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/debug_00.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/chat/scs/JA/debug_02.scs", new MappingData(c: true));
			files.Add(@"rootR.cpk/mg/tex/karuta.tex", new MappingData(c: true, skipTextMapping: true));
			files.Add(@"rootR.cpk/mnu/tex/main.tex", new MappingData(c: true, skipTextMapping: true));
			files.Add(@"rootR.cpk/mnu/tex/shop.tex", new MappingData(c: true, skipTextMapping: true));
			files.Add(@"rootR.cpk/mnu/tex/skill.tex", new MappingData(c: true, skipTextMapping: true));
			files.Add(@"rootR.cpk/mnu/tex/snd_test.tex", new MappingData(c: true, skipTextMapping: true));
			files.Add(@"rootR.cpk/movie/str/ja/TOG_S01.bin", new MappingData(c: true, u: new M().A(0, -1).EnableEmptyStrings()));
			files.Add(@"rootR.cpk/movie/str/ja/TOG_S02.bin", new MappingData(c: true, u: new M().A(0, -1).A(2, new List<int>() { -1, -1 }).A(13, new List<int>() { -1, -1 }).A(14, new List<int>() { -1, -1, -1, -1 }).A(15, -1).A(16, -1).EnableEmptyStrings()));
			files.Add(@"rootR.cpk/movie/str/ja/TOG_S03.bin", new MappingData(c: true));
			files.Add(@"rootR.cpk/movie/str/ja/TOG_S04.bin", new MappingData(c: true, u: new M().A(3, -1).A(10, new List<int>() { -1, -1, -1 }).A(14, -1).A(17, -1).EnableEmptyStrings()));
			files.Add(@"rootR.cpk/movie/str/ja/TOG_S05.bin", new MappingData(c: true, u: new M().A(0, new List<int>() { -1, -1 }).A(1, -1).A(2, new List<int>() { -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 }).A(3, -1).A(4, -1).EnableEmptyStrings()));
			files.Add(@"rootR.cpk/movie/str/ja/TOG_S06.bin", new MappingData(c: true, u: new M().A(6, -1).EnableEmptyStrings()));
			files.Add(@"rootR.cpk/movie/str/ja/TOG_S07.bin", new MappingData(c: true));
			files.Add(@"rootR.cpk/movie/str/ja/TOG_S08.bin", new MappingData(c: true));
			files.Add(@"rootR.cpk/movie/str/ja/TOG_S09.bin", new MappingData(c: true));
			files.Add(@"rootR.cpk/movie/str/ja/TOG_S10.bin", new MappingData(c: true));
			files.Add(@"rootR.cpk/movie/str/ja/TOG_S11.bin", new MappingData(c: true));
			files.Add(@"rootR.cpk/str/ja/ActInfo.bin", new MappingData(c: true, w: new W().Un(4).Un(5).Un(6).Un(8).Un(12).Un(13).Un(15).Un(21)));
			files.Add(@"rootR.cpk/str/ja/CharName.bin", new MappingData(c: true, u: new M().A(25, 24).A(60, 59).A(70, 56).A(71, 64).A(84, 59).A(86, 57).A(110, 54).A(118, 59).A(149, 101, 99, 54, 135).A(163, 117, 102, 104, 119).A(173, 135).A(174, 63).A(182, 94, 94).A(192, 152).A(194, 125, 125, 44), j: new M().A(134, 52).A(214, 133)));
			files.Add(@"rootR.cpk/str/ja/MapName.bin", new MappingData(c: true, w: new W().RP(431, 439, (o, r) => r.Substring(0, 11) + o.Substring(6)).RP(433, 439, (o, r) => r.Substring(0, 11) + o.Substring(6)).RP(435, 439, (o, r) => r.Substring(0, 11) + o.Substring(6))));
			files.Add(@"rootR.cpk/str/ja/Navigation.bin", new MappingData(c: true));
			files.Add(@"rootR.cpk/SysSub/JA/TitleTexture.tex", new MappingData(c: true, skipTextMapping: true));
			files.Add(@"rootR.cpk/SysSub/JA/TOG_SS_ChatName.dat", new MappingData(c: true));
			files.Add(@"rootR.cpk/sys/ja/SysString.bin", new MappingData(c: true, j: new M().A(141, -601), w: new W().R(34, 34).R(35, 35).R(36, 36).Sys(45).Sys(46).Sys(47).R(50, 76).Sys(53).Sys(54).Sys(55).P(56, (o, r) => r.Substring(0, 5) + r.Substring(11)).R(87, 87).R(90, "").Un(105).Un(107).Un(116).Un(122).Un(123)));
			files.Add(@"rootR.cpk/sys/FontBinary2.bin", new MappingData(c: true, skipTextMapping: true));
			files.Add(@"rootR.cpk/sys/FontTexture2.tex", new MappingData(c: true, skipTextMapping: true));
		}
	}
}
