using System.Collections.Generic;
using HyoutaUtils;

namespace ToGLocInject {
	internal static partial class Mappings {
		private static void GetFileMappingsMap0(FileFetcher _fc, Dictionary<string, MappingData> files) {
			files.Add(@"map0R.cpk/mapfile_basiR.cpk/map/sce/R/ja/basi_d01.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_basiR.cpk/map/sce/R/ja/basi_d02.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_basiR.cpk/map/sce/R/ja/basi_d03.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_basiR.cpk/map/sce/R/ja/basi_d04.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_basiR.cpk/map/sce/R/ja/basi_d05.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_basiR.cpk/map/sce/R/ja/basi_d06.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_basiR.cpk/map/sce/R/ja/basi_d07.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_basiR.cpk/map/sce/R/ja/basi_d08.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_basiR.cpk/map/sce/R/ja/basi_d09.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_basiR.cpk/map/sce/R/ja/basi_d10.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_basiR.cpk/map/sce/R/ja/basi_d11.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_basiR.cpk/map/sce/R/ja/basi_d12.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_basiR.cpk/map/sce/R/ja/basi_d13.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_basiR.cpk/map/sce/R/ja/basi_d14.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_basiR.cpk/map/sce/R/ja/basi_d15.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_basiR.cpk/map/sce/R/ja/basi_d16.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_basiR.cpk/map/sce/R/ja/basi_d17.scs", new MappingData(c: true, u: GenerateCommonU(449), j: GenerateCommonJ(449), w: new W().R(641, 425).R(643, 427)));
			files.Add(@"map0R.cpk/mapfile_basiR.cpk/map/sce/R/ja/e731_090.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_basiR.cpk/map/sce/R/ja/e731_100.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_basiR.cpk/map/sce/R/ja/e731_101.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_basiR.cpk/map/sce/R/ja/s231_001.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_briaR.cpk/map/sce/R/ja/bria_d01.scs", new MappingData(c: true, u: GenerateCommonU(458), j: GenerateCommonJ(458), w: new W().R(647, 434).R(649, 436)));
			files.Add(@"map0R.cpk/mapfile_briaR.cpk/map/sce/R/ja/bria_d02.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_briaR.cpk/map/sce/R/ja/e312_050.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_briaR.cpk/map/sce/R/ja/e312_060.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_briaR.cpk/map/sce/R/ja/e312_061.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_briaR.cpk/map/sce/R/ja/e312_070.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_briaR.cpk/map/sce/R/ja/e314_010.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_briaR.cpk/map/sce/R/ja/s211_002.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_bridR.cpk/map/sce/R/ja/brid_d01.scs", new MappingData(c: true, u: GenerateCommonU(738).A(874, 410), j: GenerateCommonJ(738).A(892, -1).A(893, 412), w: new W().R(843, 714).R(845, 716).R(570, 417).R(571, 418).R(498, 293).R(507, 308).R(519, 334).R(740, 609).R(522, 343).R(534, 379).R(548, 395).R(562, 409).R(566, 413).R(530, 357)));
			files.Add(@"map0R.cpk/mapfile_bridR.cpk/map/sce/R/ja/brid_d05.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().R(486, 267).R(487, 268).R(489, 270)));
			files.Add(@"map0R.cpk/mapfile_bridR.cpk/map/sce/R/ja/brid_d06.scs", new MappingData(c: true, u: GenerateCommonU(437), j: GenerateCommonJ(437), w: new W().R(630, 413).R(632, 415)));
			files.Add(@"map0R.cpk/mapfile_bridR.cpk/map/sce/R/ja/brid_d07.scs", new MappingData(c: true, u: GenerateCommonU(441), j: GenerateCommonJ(441), w: new W().R(634, 417).R(636, 419)));
			files.Add(@"map0R.cpk/mapfile_bridR.cpk/map/sce/R/ja/brid_d08.scs", new MappingData(c: true, u: GenerateCommonU(441), j: GenerateCommonJ(441).A(595, -1), w: new W().R(634, 417).R(636, 419)));
			files.Add(@"map0R.cpk/mapfile_bridR.cpk/map/sce/R/ja/brid_d09.scs", new MappingData(c: true, u: GenerateCommonU(448), j: GenerateCommonJ(448), w: new W().R(637, 424).R(639, 426)));
			files.Add(@"map0R.cpk/mapfile_bridR.cpk/map/sce/R/ja/brid_d10.scs", new MappingData(c: true, u: GenerateCommonU(437), j: GenerateCommonJ(437), w: new W().R(630, 413).R(632, 415)));
			files.Add(@"map0R.cpk/mapfile_bridR.cpk/map/sce/R/ja/brid_d11.scs", new MappingData(c: true, u: GenerateDefault(), j: new M().A(328, -1)));
			files.Add(@"map0R.cpk/mapfile_bridR.cpk/map/sce/R/ja/brid_d12.scs", new MappingData(c: true, u: GenerateDefault(), j: new M().A(325, -1)));
			files.Add(@"map0R.cpk/mapfile_bridR.cpk/map/sce/R/ja/brid_d13.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_bridR.cpk/map/sce/R/ja/brid_d14.scs", new MappingData(c: true, u: GenerateCommonU(454), j: GenerateCommonJ(454), w: new W().R(643, 430).R(645, 432)));
			files.Add(@"map0R.cpk/mapfile_bridR.cpk/map/sce/R/ja/brid_d15.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_bridR.cpk/map/sce/R/ja/brid_d16.scs", new MappingData(c: true, u: GenerateDefault(), j: new M().A(332, -1)));
			files.Add(@"map0R.cpk/mapfile_bridR.cpk/map/sce/R/ja/brid_d17.scs", new MappingData(c: true, u: GenerateDefault(), j: new M().A(346, -1), w: new W().R(490, 271)));
			files.Add(@"map0R.cpk/mapfile_bridR.cpk/map/sce/R/ja/e314_020.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_bridR.cpk/map/sce/R/ja/e314_030.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_bridR.cpk/map/sce/R/ja/e314_030a.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_bridR.cpk/map/sce/R/ja/e314_040.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_bridR.cpk/map/sce/R/ja/e314_040a.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_bridR.cpk/map/sce/R/ja/e314_050.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_bridR.cpk/map/sce/R/ja/e314_060.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_bridR.cpk/map/sce/R/ja/e314_060a.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_bridR.cpk/map/sce/R/ja/e314_070.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_bridR.cpk/map/sce/R/ja/e314_071.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_bridR.cpk/map/sce/R/ja/e314_080.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_bridR.cpk/map/sce/R/ja/e314_090.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_bridR.cpk/map/sce/R/ja/e314_100.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_bridR.cpk/map/sce/R/ja/e314_110.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_bridR.cpk/map/sce/R/ja/e314_120.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_bridR.cpk/map/sce/R/ja/s404_001.scs", new MappingData(c: true, u: GenerateDefault(), j: new M().A(314, 270)));
			files.Add(@"map0R.cpk/mapfile_bridR.cpk/map/sce/R/ja/s404_003.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_caveR.cpk/map/sce/R/ja/cave_d01.scs", new MappingData(c: true, u: GenerateCommonU(495), j: GenerateCommonJ(495), w: new W().Sys(105).R(685, 471).R(687, 473)));
			files.Add(@"map0R.cpk/mapfile_caveR.cpk/map/sce/R/ja/cave_d02.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_caveR.cpk/map/sce/R/ja/e210_020.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().Sys(105)));
			files.Add(@"map0R.cpk/mapfile_caveR.cpk/map/sce/R/ja/e210_030.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_caveR.cpk/map/sce/R/ja/e210_040.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().Sys(105)));
			files.Add(@"map0R.cpk/mapfile_caveR.cpk/map/sce/R/ja/e210_041.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().Sys(105)));
			files.Add(@"map0R.cpk/mapfile_caveR.cpk/map/sce/R/ja/e628_070.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_caveR.cpk/map/sce/R/ja/e628_080.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().Sys(105)));
			files.Add(@"map0R.cpk/mapfile_caveR.cpk/map/sce/R/ja/e629_120.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().Sys(105)));
			files.Add(@"map0R.cpk/mapfile_caveR.cpk/map/sce/R/ja/e629_130.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_caveR.cpk/map/sce/R/ja/e629_140.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().Sys(105)));
			files.Add(@"map0R.cpk/mapfile_caveR.cpk/map/sce/R/ja/e629_150.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_caveR.cpk/map/sce/R/ja/e629_160.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().Sys(105)));
			files.Add(@"map0R.cpk/mapfile_caveR.cpk/map/sce/R/ja/e629_161.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().Sys(105)));
			files.Add(@"map0R.cpk/mapfile_caveR.cpk/map/sce/R/ja/e629_170.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_coreR.cpk/map/sce/R/ja/core_d01.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_coreR.cpk/map/sce/R/ja/core_d02.scs", new MappingData(c: true, u: GenerateDefault(), j: new M().A(343, -2)));
			files.Add(@"map0R.cpk/mapfile_coreR.cpk/map/sce/R/ja/core_d03.scs", new MappingData(c: true, u: GenerateDefault(), j: new M().A(298, -2)));
			files.Add(@"map0R.cpk/mapfile_coreR.cpk/map/sce/R/ja/core_d04.scs", new MappingData(c: true, u: GenerateDefault().A(375, 354, 355), j: new M().A(356, 375, 376)));
			files.Add(@"map0R.cpk/mapfile_coreR.cpk/map/sce/R/ja/core_d05.scs", new MappingData(c: true, u: GenerateDefault(), j: new M().A(276, -1).A(304, -2)));
			files.Add(@"map0R.cpk/mapfile_coreR.cpk/map/sce/R/ja/core_d06.scs", new MappingData(c: true, u: GenerateDefault(), j: new M().A(339, -2)));
			files.Add(@"map0R.cpk/mapfile_coreR.cpk/map/sce/R/ja/core_d07.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_coreR.cpk/map/sce/R/ja/core_e01.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_coreR.cpk/map/sce/R/ja/e945_010.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_coreR.cpk/map/sce/R/ja/e945_020.scs", new MappingData(c: true, u: GenerateDefault(), j: new M().A(299, -2)));
			files.Add(@"map0R.cpk/mapfile_coreR.cpk/map/sce/R/ja/e945_021.scs", new MappingData(c: true, u: GenerateDefault(), j: new M().A(299, -2).A(309, -1)));
			files.Add(@"map0R.cpk/mapfile_coreR.cpk/map/sce/R/ja/e945_030.scs", new MappingData(c: true, u: GenerateDefault(), j: new M().A(305, -2).A(277, -1)));
			files.Add(@"map0R.cpk/mapfile_coreR.cpk/map/sce/R/ja/e945_031.scs", new MappingData(c: true, u: GenerateDefault(), j: new M().A(305, -2).A(277, -1)));
			files.Add(@"map0R.cpk/mapfile_coreR.cpk/map/sce/R/ja/e945_040.scs", new MappingData(c: true, u: GenerateDefault(), j: new M().A(408, -1)));
			files.Add(@"map0R.cpk/mapfile_coreR.cpk/map/sce/R/ja/e945_041.scs", new MappingData(c: true, u: GenerateDefault(), j: new M().A(369, -1)));
			files.Add(@"map0R.cpk/mapfile_coreR.cpk/map/sce/R/ja/e945_042.scs", new MappingData(c: true, u: GenerateDefault().A(292, 320), j: new M().A(323, 294)));
			files.Add(@"map0R.cpk/mapfile_coreR.cpk/map/sce/R/ja/e945_043.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_elemR.cpk/map/sce/R/ja/e942_050.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_elemR.cpk/map/sce/R/ja/e942_060.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_elemR.cpk/map/sce/R/ja/e942_061.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_elemR.cpk/map/sce/R/ja/e942_062.scs", new MappingData(c: true, u: GenerateDefault(), j: new M().A(306, -1)));
			files.Add(@"map0R.cpk/mapfile_elemR.cpk/map/sce/R/ja/e942_070.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_elemR.cpk/map/sce/R/ja/e942_071.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_elemR.cpk/map/sce/R/ja/e942_072.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_elemR.cpk/map/sce/R/ja/e942_073.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_elemR.cpk/map/sce/R/ja/e942_080.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_elemR.cpk/map/sce/R/ja/e944_011.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_elemR.cpk/map/sce/R/ja/elem_d01.scs", new MappingData(c: true, u: GenerateCommonU(443), j: GenerateCommonJ(443)));
			files.Add(@"map0R.cpk/mapfile_elemR.cpk/map/sce/R/ja/elem_d02.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_elemR.cpk/map/sce/R/ja/elem_d03.scs", new MappingData(c: true, u: GenerateCommonU(444), j: GenerateCommonJ(444)));
			files.Add(@"map0R.cpk/mapfile_elemR.cpk/map/sce/R/ja/elem_d04.scs", new MappingData(c: true, u: GenerateDefault().A(343, 272).A(376, 274, 273, 276).A(377, 275)));
			files.Add(@"map0R.cpk/mapfile_elemR.cpk/map/sce/R/ja/elem_d05.scs", new MappingData(c: true, u: GenerateCommonU(483), j: GenerateCommonJ(483)));
			files.Add(@"map0R.cpk/mapfile_elemR.cpk/map/sce/R/ja/elem_d06.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_elemR.cpk/map/sce/R/ja/elem_d07.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_elemR.cpk/map/sce/R/ja/elem_d08.scs", new MappingData(c: true, u: GenerateCommonU(443), j: GenerateCommonJ(443)));
			files.Add(@"map0R.cpk/mapfile_elemR.cpk/map/sce/R/ja/elem_d09.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_elemR.cpk/map/sce/R/ja/elem_d10.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_elemR.cpk/map/sce/R/ja/elem_d11.scs", new MappingData(c: true, u: GenerateCommonU(474), j: GenerateCommonJ(474)));
			files.Add(@"map0R.cpk/mapfile_ff12R.cpk/map/sce/R/ja/e523_010.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().R(489, 270)));
			files.Add(@"map0R.cpk/mapfile_ff12R.cpk/map/sce/R/ja/e523_020.scs", new MappingData(c: true, u: GenerateDefault().A(274, 272, 273, 271), w: new W().RP(488, 269, (o, r) => r.Substring(6))));
			files.Add(@"map0R.cpk/mapfile_ff12R.cpk/map/sce/R/ja/e628_055.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().R(489, 270)));
			files.Add(@"map0R.cpk/mapfile_ff12R.cpk/map/sce/R/ja/fend_f12.scs", new MappingData(c: true, u: GenerateCommonU(588).A(379, 377, 378, 376).A(660, -1).A(662, -1), j: GenerateCommonJ(593 - 2).A(668, -1).A(666, -1), w: new W().R(502, 291).R(515, 318).R(517, 320).R(652, 460).R(754, 564).R(756, 566).RP(563, 374, (o, r) => r.Substring(6))));
			files.Add(@"map0R.cpk/mapfile_ff12R.cpk/map/sce/R/ja/port_i04.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_ff12R.cpk/map/sce/R/ja/port_t04.scs", new MappingData(c: true, u: GenerateDefault(), j: new M().A(293, 291), w: new W().R(530, 348).R(649, 467)));
			files.Add(@"map0R.cpk/mapfile_ff13R.cpk/map/sce/R/ja/fend_f13.scs", new MappingData(c: true, u: GenerateCommonU(524).A(356, 352, 354, 355), j: GenerateCommonJ(528 - 2).A(358, 354), w: new W().R(494, 280).R(694, 500).R(696, 502)));
			files.Add(@"map0R.cpk/mapfile_ff13R.cpk/map/sce/R/ja/koya_r08.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_ff13R.cpk/map/sce/R/ja/s230_001.scs", new MappingData(c: true, u: GenerateDefault().A(288, 284, 286, 287), j: new M().A(290, 286)));
			files.Add(@"map0R.cpk/mapfile_ff13R.cpk/map/sce/R/ja/s230_002.scs", new MappingData(c: true, u: GenerateDefault().A(288, 284, 286, 287), j: new M().A(290, 286)));
			files.Add(@"map0R.cpk/mapfile_ff14R.cpk/map/sce/R/ja/e523_070.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().Sys(107)));
			files.Add(@"map0R.cpk/mapfile_ff14R.cpk/map/sce/R/ja/fend_f14.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().R(536, 330)));
			files.Add(@"map0R.cpk/mapfile_ff14R.cpk/map/sce/R/ja/port_i05.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_ff14R.cpk/map/sce/R/ja/port_t05.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().Sys(107).R(490, 271).R(622, 442)));
			files.Add(@"map0R.cpk/mapfile_ff14R.cpk/map/sce/R/ja/s234_001.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().R(488, 269)));
			files.Add(@"map0R.cpk/mapfile_ff15R.cpk/map/sce/R/ja/e523_120.scs", new MappingData(c: true, u: GenerateDefault().A(273, 272, 272, 272, 272, 272).A(274, 272).A(277, -4).A(278, 277)));
			files.Add(@"map0R.cpk/mapfile_ff15R.cpk/map/sce/R/ja/e523_130.scs", new MappingData(c: true, u: GenerateDefault().A(273, 272, 272, 272, 272, 272).A(274, 272).A(277, -4).A(278, 277)));
			files.Add(@"map0R.cpk/mapfile_ff15R.cpk/map/sce/R/ja/e523_131.scs", new MappingData(c: true, u: GenerateDefault().A(273, 272, 272, 272, 272, 272).A(274, 272).A(277, -4).A(278, 277)));
			files.Add(@"map0R.cpk/mapfile_ff15R.cpk/map/sce/R/ja/fend_f15.scs", new MappingData(c: true, u: GenerateCommonU(559).A(298, 297, 297, 297, 297, 297).A(299, 297).A(342, 341), j: GenerateCommonJ(567 - 2).A(278, 276), w: new W().R(635, 431).R(737, 535).R(739, 537)));
			files.Add(@"map0R.cpk/mapfile_ff15R.cpk/map/sce/R/ja/s233_001.scs", new MappingData(c: true, u: GenerateDefault().A(273, 272, 272, 272, 272, 272).A(274, 272).A(277, -4).A(278, 277)));
			files.Add(@"map0R.cpk/mapfile_ff16R.cpk/map/sce/R/ja/fend_f16.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().R(615, 408)));
			files.Add(@"map0R.cpk/mapfile_ff17R.cpk/map/sce/R/ja/e526_030.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().R(485, 266)));
			files.Add(@"map0R.cpk/mapfile_ff17R.cpk/map/sce/R/ja/e629_080.scs", new MappingData(c: true, u: GenerateDefault().A(368, 372), j: new M().A(375, 370), w: new W().R(485, 266)));
			files.Add(@"map0R.cpk/mapfile_ff17R.cpk/map/sce/R/ja/e629_090.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().R(489, 270)));
			files.Add(@"map0R.cpk/mapfile_ff17R.cpk/map/sce/R/ja/e629_110.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().R(489, 270)));
			files.Add(@"map0R.cpk/mapfile_ff17R.cpk/map/sce/R/ja/e629_111.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().R(489, 270)));
			files.Add(@"map0R.cpk/mapfile_ff17R.cpk/map/sce/R/ja/fend_f17.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().R(532, 325).R(615, 408)));
			files.Add(@"map0R.cpk/mapfile_ff19R.cpk/map/sce/R/ja/e730_020.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_ff19R.cpk/map/sce/R/ja/e731_010.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_ff19R.cpk/map/sce/R/ja/e731_080.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_ff19R.cpk/map/sce/R/ja/fodr_f19.scs", new MappingData(c: true, u: GenerateCommonU(498), j: GenerateCommonJ(498), w: new W().R(687, 474).R(689, 476)));
			files.Add(@"map0R.cpk/mapfile_ff20R.cpk/map/sce/R/ja/e731_110.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_ff20R.cpk/map/sce/R/ja/fodr_f20.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_ff20R.cpk/map/sce/R/ja/s243_001.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_foreR.cpk/map/sce/R/ja/e206_010.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_foreR.cpk/map/sce/R/ja/e206_011.scs", new MappingData(c: true, u: GenerateDefault(), j: new M(new List<E>() { new E(364, 324) })));
			files.Add(@"map0R.cpk/mapfile_foreR.cpk/map/sce/R/ja/e206_011t.scs", new MappingData(c: true, u: GenerateDefault(), j: new M(new List<E>() { new E(363, 323) })));
			files.Add(@"map0R.cpk/mapfile_foreR.cpk/map/sce/R/ja/e206_020.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_foreR.cpk/map/sce/R/ja/e206_031.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_foreR.cpk/map/sce/R/ja/e206_032.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_foreR.cpk/map/sce/R/ja/e206_033.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_foreR.cpk/map/sce/R/ja/fore_d01.scs", new MappingData(c: true, u: GenerateCommonU(530), j: GenerateCommonJ(530), w: new W().R(706, 506).R(708, 508)));
			files.Add(@"map0R.cpk/mapfile_foreR.cpk/map/sce/R/ja/s107_001.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_foreR.cpk/map/sce/R/ja/s207_001.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_gentR.cpk/map/sce/R/ja/gent_d01.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_gentR.cpk/map/sce/R/ja/gent_d02.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_gentR.cpk/map/sce/R/ja/s249_001.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_gentR.cpk/map/sce/R/ja/s413_001.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_gentR.cpk/map/sce/R/ja/s413_002.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_gentR.cpk/map/sce/R/ja/s413_003.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_icebR.cpk/map/sce/R/ja/e525_080.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().Sys(105).Sys(107).Sys(108)));
			files.Add(@"map0R.cpk/mapfile_icebR.cpk/map/sce/R/ja/e525_090.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().Sys(105).Sys(107).Sys(108)));
			files.Add(@"map0R.cpk/mapfile_icebR.cpk/map/sce/R/ja/e525_091.scs", new MappingData(c: true, u: GenerateDefault().A(368, -1)));
			files.Add(@"map0R.cpk/mapfile_icebR.cpk/map/sce/R/ja/e525_092.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_icebR.cpk/map/sce/R/ja/e525_093.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_icebR.cpk/map/sce/R/ja/e836_020.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().R(546, 327)));
			files.Add(@"map0R.cpk/mapfile_icebR.cpk/map/sce/R/ja/e940_030.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_icebR.cpk/map/sce/R/ja/e940_040.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_icebR.cpk/map/sce/R/ja/e940_041.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_icebR.cpk/map/sce/R/ja/iceb_d01.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_icebR.cpk/map/sce/R/ja/iceb_d02.scs", new MappingData(c: true, u: GenerateCommonU(501), j: GenerateCommonJ(501), w: new W().R(690, 477).R(692, 479).Sys(105).Sys(107).Sys(108)));
			files.Add(@"map0R.cpk/mapfile_icebR.cpk/map/sce/R/ja/iceb_d03.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_icebR.cpk/map/sce/R/ja/iceb_d04.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_icebR.cpk/map/sce/R/ja/iceb_d05.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_icebR.cpk/map/sce/R/ja/iceb_d08.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_icebR.cpk/map/sce/R/ja/iceb_d09.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_icebR.cpk/map/sce/R/ja/iceb_d10.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_icebR.cpk/map/sce/R/ja/iceb_d11.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_icebR.cpk/map/sce/R/ja/iceb_e01.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_icebR.cpk/map/sce/R/ja/iceb_e02.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_icebR.cpk/map/sce/R/ja/s240_001.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_ironR.cpk/map/sce/R/ja/e525_030.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_ironR.cpk/map/sce/R/ja/e525_040.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_ironR.cpk/map/sce/R/ja/e525_041.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_ironR.cpk/map/sce/R/ja/e525_050.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_ironR.cpk/map/sce/R/ja/e525_060.scs", new MappingData(c: true, u: GenerateDefault().A(349, 352), j: new M().A(355, 351)));
			files.Add(@"map0R.cpk/mapfile_ironR.cpk/map/sce/R/ja/e525_070.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_ironR.cpk/map/sce/R/ja/iron_d01.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_ironR.cpk/map/sce/R/ja/iron_d02.scs", new MappingData(c: true, u: GenerateCommonU(540), j: GenerateCommonJ(540), w: new W().R(696, 516).R(698, 518)));
			files.Add(@"map0R.cpk/mapfile_ironR.cpk/map/sce/R/ja/iron_d03.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_ironR.cpk/map/sce/R/ja/iron_d04.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_ironR.cpk/map/sce/R/ja/iron_d05.scs", new MappingData(c: true, u: GenerateDefault(), j: new M().A(292, 289), w: new W().R(486, 267).R(487, 268).R(488, 269).R(513, 295)));
			files.Add(@"map0R.cpk/mapfile_ironR.cpk/map/sce/R/ja/iron_d06.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_ironR.cpk/map/sce/R/ja/iron_d07.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_ironR.cpk/map/sce/R/ja/iron_d08.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_ironR.cpk/map/sce/R/ja/iron_d09.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_ironR.cpk/map/sce/R/ja/iron_d10.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_ironR.cpk/map/sce/R/ja/iron_d11.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_ironR.cpk/map/sce/R/ja/iron_d12.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_ironR.cpk/map/sce/R/ja/iron_d13.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_ironR.cpk/map/sce/R/ja/iron_d14.scs", new MappingData(c: true, u: GenerateCommonU(490), j: GenerateCommonJ(490), w: new W().R(679, 466).R(681, 468)));
			files.Add(@"map0R.cpk/mapfile_ironR.cpk/map/sce/R/ja/iron_d15.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_ironR.cpk/map/sce/R/ja/iron_d16.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_ironR.cpk/map/sce/R/ja/iron_d17.scs", new MappingData(c: true, u: GenerateDefault().A(279, -1)));
			files.Add(@"map0R.cpk/mapfile_ironR.cpk/map/sce/R/ja/iron_d18.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_ironR.cpk/map/sce/R/ja/iron_d19.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_ironR.cpk/map/sce/R/ja/s128_001.scs", new MappingData(c: true, u: GenerateDefault(), j: new M().A(365, 363)));
			files.Add(@"map0R.cpk/mapfile_ironR.cpk/map/sce/R/ja/s236_001.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_koneR.cpk/map/sce/R/ja/e731_030.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_koneR.cpk/map/sce/R/ja/e731_040.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_koneR.cpk/map/sce/R/ja/e731_050.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().R(510, 291)));
			files.Add(@"map0R.cpk/mapfile_koneR.cpk/map/sce/R/ja/e731_060.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().R(510, 291)));
			files.Add(@"map0R.cpk/mapfile_koneR.cpk/map/sce/R/ja/e731_061.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().R(510, 291)));
			files.Add(@"map0R.cpk/mapfile_koneR.cpk/map/sce/R/ja/e731_062.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().R(510, 291)));
			files.Add(@"map0R.cpk/mapfile_koneR.cpk/map/sce/R/ja/e731_063.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().R(510, 291)));
			files.Add(@"map0R.cpk/mapfile_koneR.cpk/map/sce/R/ja/e731_064.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().R(510, 291)));
			files.Add(@"map0R.cpk/mapfile_koneR.cpk/map/sce/R/ja/e731_065.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().R(510, 291)));
			files.Add(@"map0R.cpk/mapfile_koneR.cpk/map/sce/R/ja/e731_066.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().R(514, 295)));
			files.Add(@"map0R.cpk/mapfile_koneR.cpk/map/sce/R/ja/e731_070.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_koneR.cpk/map/sce/R/ja/e835_030.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_koneR.cpk/map/sce/R/ja/e835_050.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_koneR.cpk/map/sce/R/ja/kone_d02.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_koneR.cpk/map/sce/R/ja/kone_d03.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_koneR.cpk/map/sce/R/ja/kone_d04.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_koneR.cpk/map/sce/R/ja/kone_d05.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_koneR.cpk/map/sce/R/ja/kone_d06.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_koneR.cpk/map/sce/R/ja/kone_d07.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_koneR.cpk/map/sce/R/ja/kone_d08.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_koneR.cpk/map/sce/R/ja/kone_d09.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_koneR.cpk/map/sce/R/ja/kone_d10.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_koneR.cpk/map/sce/R/ja/kone_d11.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_koneR.cpk/map/sce/R/ja/kone_d12.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().Sys(105)));
			files.Add(@"map0R.cpk/mapfile_koneR.cpk/map/sce/R/ja/kone_d13.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_koneR.cpk/map/sce/R/ja/kone_d14.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_koneR.cpk/map/sce/R/ja/kone_d15.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_koneR.cpk/map/sce/R/ja/kone_d16.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_koneR.cpk/map/sce/R/ja/kone_d17.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_koneR.cpk/map/sce/R/ja/kone_d18.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_koneR.cpk/map/sce/R/ja/kone_d19.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_koneR.cpk/map/sce/R/ja/kone_d20.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_koneR.cpk/map/sce/R/ja/kone_d21.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_koneR.cpk/map/sce/R/ja/kone_d22.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_koneR.cpk/map/sce/R/ja/kone_d23.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_koneR.cpk/map/sce/R/ja/kone_d24.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_koneR.cpk/map/sce/R/ja/kone_d25.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_koneR.cpk/map/sce/R/ja/kone_d26.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_koneR.cpk/map/sce/R/ja/kone_d29.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_koneR.cpk/map/sce/R/ja/kone_d30.scs", new MappingData(c: true, u: GenerateCommonU(463), j: GenerateCommonJ(463), w: new W().R(513, 294).R(656, 439).R(658, 441)));
			files.Add(@"map0R.cpk/mapfile_koneR.cpk/map/sce/R/ja/kone_e01.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_koneR.cpk/map/sce/R/ja/s242_001.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().R(555, 336)));
			files.Add(@"map0R.cpk/mapfile_koneR.cpk/map/sce/R/ja/s244_002.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_koneR.cpk/map/sce/R/ja/s416_003.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_koneR.cpk/map/sce/R/ja/s416_004.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_kotR.cpk/map/sce/R/ja/e526_060.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_kotR.cpk/map/sce/R/ja/e526_070.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_kotR.cpk/map/sce/R/ja/e526_071.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_kotR.cpk/map/sce/R/ja/e526_072.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_kotR.cpk/map/sce/R/ja/e731_020.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_kotR.cpk/map/sce/R/ja/e833_010.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_kotR.cpk/map/sce/R/ja/e833_020.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_kotR.cpk/map/sce/R/ja/e833_030.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_kotR.cpk/map/sce/R/ja/e833_031.scs", new MappingData(c: true, u: new M(new List<E> { new E(60, 36), new E(81, 11), new E(350, 354) }), j: new M(new List<E> { new E(357, 352) })));
			files.Add(@"map0R.cpk/mapfile_kotR.cpk/map/sce/R/ja/e833_032.scs", new MappingData(c: true, u: GenerateDefault(), j: new M().A(361, -1)));
			files.Add(@"map0R.cpk/mapfile_kotR.cpk/map/sce/R/ja/e833_033.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_kotR.cpk/map/sce/R/ja/kot1_d01.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_kotR.cpk/map/sce/R/ja/kot1_d02.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_kotR.cpk/map/sce/R/ja/kot2_d01.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_kotR.cpk/map/sce/R/ja/kot2_d02.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_kotR.cpk/map/sce/R/ja/kot2_d03.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_kotR.cpk/map/sce/R/ja/kot2_d04.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_kotR.cpk/map/sce/R/ja/kot2_d05.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_kotR.cpk/map/sce/R/ja/kot2_d06.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_kotR.cpk/map/sce/R/ja/kot2_d07.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_kotR.cpk/map/sce/R/ja/kot2_d08.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_kotR.cpk/map/sce/R/ja/kot2_d09.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_kotR.cpk/map/sce/R/ja/kot2_d10.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_kotR.cpk/map/sce/R/ja/kot2_d11.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_kotR.cpk/map/sce/R/ja/kot2_d12.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_kotR.cpk/map/sce/R/ja/kot2_d13.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_kotR.cpk/map/sce/R/ja/kot2_d14.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_kotR.cpk/map/sce/R/ja/kot2_d15.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_kotR.cpk/map/sce/R/ja/kot2_d16.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_kotR.cpk/map/sce/R/ja/kot2_d17.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_kotR.cpk/map/sce/R/ja/kot2_d18.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_kotR.cpk/map/sce/R/ja/kot2_d19.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_kotR.cpk/map/sce/R/ja/kot2_d20.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_kotR.cpk/map/sce/R/ja/kot2_d21.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_kotR.cpk/map/sce/R/ja/kot2_d22.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_kotR.cpk/map/sce/R/ja/kot2_d23.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_kotR.cpk/map/sce/R/ja/kot2_d24.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_kotR.cpk/map/sce/R/ja/kot2_d25.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_kotR.cpk/map/sce/R/ja/kot2_d26.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_kotR.cpk/map/sce/R/ja/kot2_d27.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_kotR.cpk/map/sce/R/ja/s244_001.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_lasR.cpk/map/sce/R/ja/e835_010.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_lasR.cpk/map/sce/R/ja/e835_020.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_lasR.cpk/map/sce/R/ja/e835_040.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_lasR.cpk/map/sce/R/ja/e835_140.scs", new MappingData(c: true, u: GenerateDefault(), j: new M().A(379, -1)));
			files.Add(@"map0R.cpk/mapfile_lasR.cpk/map/sce/R/ja/e835_141.scs", new MappingData(c: true, u: GenerateDefault(), j: new M().A(319, -1)));
			files.Add(@"map0R.cpk/mapfile_lasR.cpk/map/sce/R/ja/e835_142.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_lasR.cpk/map/sce/R/ja/e835_150.scs", new MappingData(c: true, u: GenerateDefault(), j: new M().A(320, -1), w: new W().Sys(107)));
			files.Add(@"map0R.cpk/mapfile_lasR.cpk/map/sce/R/ja/e835_160.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().Sys(104)));
			files.Add(@"map0R.cpk/mapfile_lasR.cpk/map/sce/R/ja/e835_170.scs", new MappingData(c: true, u: GenerateDefault(), j: new M().A(376, -1), w: new W().Sys(105)));
			files.Add(@"map0R.cpk/mapfile_lasR.cpk/map/sce/R/ja/e835_180.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_lasR.cpk/map/sce/R/ja/e941_011.scs", new MappingData(c: true, u: GenerateDefault(), j: new M().A(318, -1)));
			files.Add(@"map0R.cpk/mapfile_lasR.cpk/map/sce/R/ja/e944_020.scs", new MappingData(c: true, u: GenerateDefault(), j: new M().A(318, -1)));
			files.Add(@"map0R.cpk/mapfile_lasR.cpk/map/sce/R/ja/las1_d01.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_lasR.cpk/map/sce/R/ja/las2_d01.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_lasR.cpk/map/sce/R/ja/las2_d02.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_lasR.cpk/map/sce/R/ja/las2_d03.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_lasR.cpk/map/sce/R/ja/las3_d01.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_lasR.cpk/map/sce/R/ja/las3_d02.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().RP(514, 297, (o, r) => r.ReplaceSubstring(0, 9, o, 0, 9))));
			files.Add(@"map0R.cpk/mapfile_lasR.cpk/map/sce/R/ja/las4_d01.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_lasR.cpk/map/sce/R/ja/las4_d02.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().Sys(104)));
			files.Add(@"map0R.cpk/mapfile_lasR.cpk/map/sce/R/ja/las4_e01.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().Sys(107)));
			files.Add(@"map0R.cpk/mapfile_montR.cpk/map/sce/R/ja/e101_010.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_montR.cpk/map/sce/R/ja/e101_020.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().Sys(104)));
			files.Add(@"map0R.cpk/mapfile_montR.cpk/map/sce/R/ja/e101_021.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().Sys(104)));
			files.Add(@"map0R.cpk/mapfile_montR.cpk/map/sce/R/ja/e101_022.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_montR.cpk/map/sce/R/ja/e103_040.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().Sys(104)));
			files.Add(@"map0R.cpk/mapfile_montR.cpk/map/sce/R/ja/e103_041.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_montR.cpk/map/sce/R/ja/e103_050.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().Sys(104).Sys(105).RP(490, 270, (o, r) => r.ReplaceSubstring(122, 6, o, 46, 9))));
			files.Add(@"map0R.cpk/mapfile_montR.cpk/map/sce/R/ja/e103_060.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().Sys(104).Sys(105).RP(490, 270, (o, r) => r.ReplaceSubstring(122, 6, o, 46, 9))));
			files.Add(@"map0R.cpk/mapfile_montR.cpk/map/sce/R/ja/e103_061.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().Sys(104).Sys(105).RP(490, 270, (o, r) => r.ReplaceSubstring(122, 6, o, 46, 9))));
			files.Add(@"map0R.cpk/mapfile_montR.cpk/map/sce/R/ja/e103_070.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_montR.cpk/map/sce/R/ja/e208_030.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_montR.cpk/map/sce/R/ja/e208_031.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_montR.cpk/map/sce/R/ja/e208_040.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_montR.cpk/map/sce/R/ja/e418_030.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().Sys(104)));
			files.Add(@"map0R.cpk/mapfile_montR.cpk/map/sce/R/ja/e834_070.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().Sys(104)));
			files.Add(@"map0R.cpk/mapfile_montR.cpk/map/sce/R/ja/e946_010.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_montR.cpk/map/sce/R/ja/e946_011.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_montR.cpk/map/sce/R/ja/e946_012.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_montR.cpk/map/sce/R/ja/e946_013.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_montR.cpk/map/sce/R/ja/eplg_e01.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_montR.cpk/map/sce/R/ja/eplg_e02.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_montR.cpk/map/sce/R/ja/eplg_e03.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_montR.cpk/map/sce/R/ja/mont_d01.scs", new MappingData(c: true, u: GenerateCommonU(483), j: GenerateCommonJ(483), w: new W().R(672, 459).R(674, 461)));
			files.Add(@"map0R.cpk/mapfile_montR.cpk/map/sce/R/ja/mont_d02.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().Sys(104)));
			files.Add(@"map0R.cpk/mapfile_montR.cpk/map/sce/R/ja/mont_d03.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().Sys(104).Sys(105).RP(489, 269, (o, r) => r.ReplaceSubstring(122, 6, o, 46, 9))));
			files.Add(@"map0R.cpk/mapfile_montR.cpk/map/sce/R/ja/s202_001.scs", new MappingData(c: true, u: GenerateDefault().A(321, -2).A(327, -1), w: new W().Sys(104).Sys(548)));
			files.Add(@"map0R.cpk/mapfile_rockR.cpk/map/sce/R/ja/e419_040.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_rockR.cpk/map/sce/R/ja/e419_050.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_rockR.cpk/map/sce/R/ja/e419_060.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_rockR.cpk/map/sce/R/ja/e419_061.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_rockR.cpk/map/sce/R/ja/e419_070.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_rockR.cpk/map/sce/R/ja/e419_080.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_rockR.cpk/map/sce/R/ja/e419_081.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_rockR.cpk/map/sce/R/ja/e419_090.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_rockR.cpk/map/sce/R/ja/rock_d01.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_rockR.cpk/map/sce/R/ja/rock_d02.scs", new MappingData(c: true, u: GenerateDefault(), j: new M().A(372, -1)));
			files.Add(@"map0R.cpk/mapfile_rockR.cpk/map/sce/R/ja/rock_d03.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_rockR.cpk/map/sce/R/ja/rock_e01.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sandR.cpk/map/sce/R/ja/sand_d01.scs", new MappingData(c: true, u: GenerateDefault(), j: new M().A(390, -1)));
			files.Add(@"map0R.cpk/mapfile_sandR.cpk/map/sce/R/ja/sand_d02.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().R(494, 275)));
			files.Add(@"map0R.cpk/mapfile_sandR.cpk/map/sce/R/ja/sand_d03.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sandR.cpk/map/sce/R/ja/sand_d04.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sandR.cpk/map/sce/R/ja/sand_d05.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sandR.cpk/map/sce/R/ja/sand_d06.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sandR.cpk/map/sce/R/ja/sand_d07.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sandR.cpk/map/sce/R/ja/sand_d08.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sandR.cpk/map/sce/R/ja/sand_d09.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sandR.cpk/map/sce/R/ja/sand_d10.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sandR.cpk/map/sce/R/ja/sand_d11.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sandR.cpk/map/sce/R/ja/sand_d12.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sandR.cpk/map/sce/R/ja/sand_d13.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sandR.cpk/map/sce/R/ja/sand_d14.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sandR.cpk/map/sce/R/ja/sand_d15.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sandR.cpk/map/sce/R/ja/sand_d16.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sf08R.cpk/map/sce/R/ja/s213_001.scs", new MappingData(c: true, u: GenerateDefault().A(269, 267), w: new W().R(548, 328)));
			files.Add(@"map0R.cpk/mapfile_sf08R.cpk/map/sce/R/ja/stra_f08.scs", new MappingData(c: true, u: GenerateDefault().A(340, 338), w: new W().R(497, 281).R(501, 294)));
			files.Add(@"map0R.cpk/mapfile_sf09R.cpk/map/sce/R/ja/koya_r05.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sf09R.cpk/map/sce/R/ja/s222_002.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sf09R.cpk/map/sce/R/ja/stra_f09.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().R(628, 427)));
			files.Add(@"map0R.cpk/mapfile_sf10R.cpk/map/sce/R/ja/s221_002.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sf10R.cpk/map/sce/R/ja/s221_005.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sf10R.cpk/map/sce/R/ja/stra_f10.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sf11R.cpk/map/sce/R/ja/e522_010.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sf11R.cpk/map/sce/R/ja/port_i03.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sf11R.cpk/map/sce/R/ja/port_t03.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().R(497, 283).R(525, 334).R(662, 475)));
			files.Add(@"map0R.cpk/mapfile_sf11R.cpk/map/sce/R/ja/s219_002.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sf11R.cpk/map/sce/R/ja/stra_f11.scs", new MappingData(c: true, u: GenerateCommonU(503), j: GenerateCommonJ(503), w: new W().R(678, 479).R(680, 481)));
			files.Add(@"map0R.cpk/mapfile_sf18R.cpk/map/sce/R/ja/e421_020.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sf18R.cpk/map/sce/R/ja/s216_001.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sf18R.cpk/map/sce/R/ja/stra_f18.scs", new MappingData(c: true, u: GenerateDefault().A(285, 278), w: new W().R(622, 415)));
			files.Add(@"map0R.cpk/mapfile_sneeR.cpk/map/sce/R/ja/e524_040.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sneeR.cpk/map/sce/R/ja/e524_050.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sneeR.cpk/map/sce/R/ja/e524_051.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sneeR.cpk/map/sce/R/ja/e524_060.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sneeR.cpk/map/sce/R/ja/s134_001.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sneeR.cpk/map/sce/R/ja/s239_001.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sneeR.cpk/map/sce/R/ja/s239_002.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().Sys(104)));
			files.Add(@"map0R.cpk/mapfile_sneeR.cpk/map/sce/R/ja/snee_d01.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sneeR.cpk/map/sce/R/ja/snee_d02.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sneeR.cpk/map/sce/R/ja/snee_d03.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sneeR.cpk/map/sce/R/ja/snee_d04.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sneeR.cpk/map/sce/R/ja/snee_d05.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sneeR.cpk/map/sce/R/ja/snee_d06.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sneeR.cpk/map/sce/R/ja/snee_d07.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sneeR.cpk/map/sce/R/ja/snee_d08.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sneeR.cpk/map/sce/R/ja/snee_d09.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sneeR.cpk/map/sce/R/ja/snee_d10.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sneeR.cpk/map/sce/R/ja/snee_d11.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sneeR.cpk/map/sce/R/ja/snee_d12.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().Sys(104)));
			files.Add(@"map0R.cpk/mapfile_sneeR.cpk/map/sce/R/ja/snee_d13.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sneeR.cpk/map/sce/R/ja/snee_d14.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sneeR.cpk/map/sce/R/ja/snee_d15.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sneeR.cpk/map/sce/R/ja/snee_d16.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sneeR.cpk/map/sce/R/ja/snee_d17.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sneeR.cpk/map/sce/R/ja/snee_d18.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sneeR.cpk/map/sce/R/ja/snee_d19.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sneeR.cpk/map/sce/R/ja/snee_d20.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sneeR.cpk/map/sce/R/ja/snee_d21.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().Sys(105)));
			files.Add(@"map0R.cpk/mapfile_sneeR.cpk/map/sce/R/ja/snee_d22.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().Sys(104)));
			files.Add(@"map0R.cpk/mapfile_sneeR.cpk/map/sce/R/ja/snee_d23.scs", new MappingData(c: true, u: GenerateCommonU(479), j: GenerateCommonJ(479), w: new W().R(668, 455).R(670, 457)));
			files.Add(@"map0R.cpk/mapfile_sneeR.cpk/map/sce/R/ja/snee_d24.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sneeR.cpk/map/sce/R/ja/snee_d25.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().Sys(104)));
			files.Add(@"map0R.cpk/mapfile_sneeR.cpk/map/sce/R/ja/snee_d26.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sneeR.cpk/map/sce/R/ja/snee_d27.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sneeR.cpk/map/sce/R/ja/snee_d28.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().Sys(104)));
			files.Add(@"map0R.cpk/mapfile_sneeR.cpk/map/sce/R/ja/snee_d29.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_snowR.cpk/map/sce/R/ja/e629_100.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_snowR.cpk/map/sce/R/ja/snow_d01.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_snowR.cpk/map/sce/R/ja/snow_d02.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().R(487, 268)));
			files.Add(@"map0R.cpk/mapfile_snowR.cpk/map/sce/R/ja/snow_d03.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_snowR.cpk/map/sce/R/ja/snow_d04.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_snowR.cpk/map/sce/R/ja/snow_d05.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_snowR.cpk/map/sce/R/ja/snow_d06.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_snowR.cpk/map/sce/R/ja/snow_d07.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_snowR.cpk/map/sce/R/ja/snow_d08.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_snowR.cpk/map/sce/R/ja/snow_d09.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_snowR.cpk/map/sce/R/ja/snow_d10.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_snowR.cpk/map/sce/R/ja/snow_d11.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_snowR.cpk/map/sce/R/ja/snow_d12.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_snowR.cpk/map/sce/R/ja/snow_d13.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_snowR.cpk/map/sce/R/ja/snow_d14.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_snowR.cpk/map/sce/R/ja/snow_d15.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_snowR.cpk/map/sce/R/ja/snow_d16.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_snowR.cpk/map/sce/R/ja/snow_d17.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_snowR.cpk/map/sce/R/ja/snow_d18.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_snowR.cpk/map/sce/R/ja/snow_d19.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_snowR.cpk/map/sce/R/ja/snow_d20.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_snowR.cpk/map/sce/R/ja/snow_d21.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_snowR.cpk/map/sce/R/ja/snow_d22.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_snowR.cpk/map/sce/R/ja/snow_d23.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_snowR.cpk/map/sce/R/ja/snow_d24.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_snowR.cpk/map/sce/R/ja/snow_d25.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_snowR.cpk/map/sce/R/ja/snow_d26.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_snowR.cpk/map/sce/R/ja/snow_d27.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_snowR.cpk/map/sce/R/ja/snow_d28.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sofiR.cpk/map/sce/R/ja/e942_010.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sofiR.cpk/map/sce/R/ja/e943_010.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sofiR.cpk/map/sce/R/ja/e943_020.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sofiR.cpk/map/sce/R/ja/e943_030.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sofiR.cpk/map/sce/R/ja/e943_031.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sofiR.cpk/map/sce/R/ja/e943_040.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sofiR.cpk/map/sce/R/ja/sofi_d01.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sofiR.cpk/map/sce/R/ja/sofi_d02.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_sofiR.cpk/map/sce/R/ja/sofi_e03.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_stdaR.cpk/map/sce/R/ja/e420_080.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_stdaR.cpk/map/sce/R/ja/e420_090.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_stdaR.cpk/map/sce/R/ja/e420_091.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_stdaR.cpk/map/sce/R/ja/e941_050.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_stdaR.cpk/map/sce/R/ja/e941_051.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_stdaR.cpk/map/sce/R/ja/e941_060.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_stdaR.cpk/map/sce/R/ja/e941_061.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_stdaR.cpk/map/sce/R/ja/e941_070.scs", new MappingData(c: true, u: GenerateDefault(), j: new M().A(313, -1)));
			files.Add(@"map0R.cpk/mapfile_stdaR.cpk/map/sce/R/ja/stda_d01.scs", new MappingData(c: true, u: GenerateCommonU(526), j: GenerateCommonJ(526).A(721, -1), w: new W().R(630, 688)));
			files.Add(@"map0R.cpk/mapfile_stdaR.cpk/map/sce/R/ja/stda_d02.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_und1R.cpk/map/sce/R/ja/e939_010.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_und1R.cpk/map/sce/R/ja/e939_020.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_und1R.cpk/map/sce/R/ja/e939_021.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_und1R.cpk/map/sce/R/ja/e939_030.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_und1R.cpk/map/sce/R/ja/e939_040.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_und1R.cpk/map/sce/R/ja/e939_050.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_und1R.cpk/map/sce/R/ja/e939_060.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_und1R.cpk/map/sce/R/ja/e939_070.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_und1R.cpk/map/sce/R/ja/e939_071.scs", new MappingData(c: true, u: GenerateDefault(), j: new M().A(376, -1)));
			files.Add(@"map0R.cpk/mapfile_und1R.cpk/map/sce/R/ja/e939_072.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_und1R.cpk/map/sce/R/ja/und1_d01.scs", new MappingData(c: true, u: GenerateCommonU(463), j: GenerateCommonJ(463)));
			files.Add(@"map0R.cpk/mapfile_und1R.cpk/map/sce/R/ja/und1_d02.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_varoR.cpk/map/sce/R/ja/e315_020.scs", new MappingData(c: true, u: GenerateDefault().A(268, -1)));
			files.Add(@"map0R.cpk/mapfile_varoR.cpk/map/sce/R/ja/e315_030.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_varoR.cpk/map/sce/R/ja/e315_040.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_varoR.cpk/map/sce/R/ja/e315_041.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_varoR.cpk/map/sce/R/ja/e315_050.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_varoR.cpk/map/sce/R/ja/e316_010.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_varoR.cpk/map/sce/R/ja/e316_020.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_varoR.cpk/map/sce/R/ja/e316_030.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_varoR.cpk/map/sce/R/ja/e418_150.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_varoR.cpk/map/sce/R/ja/e938_010.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_varoR.cpk/map/sce/R/ja/e938_020.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_varoR.cpk/map/sce/R/ja/e938_021.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_varoR.cpk/map/sce/R/ja/s211_003.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_varoR.cpk/map/sce/R/ja/s214_002.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_varoR.cpk/map/sce/R/ja/s214_003.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_varoR.cpk/map/sce/R/ja/s414_003.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_varoR.cpk/map/sce/R/ja/s456_002.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_varoR.cpk/map/sce/R/ja/varo_d01.scs", new MappingData(c: true, u: GenerateCommonU(447).A(275, -1), j: GenerateCommonJ(448), w: new W().R(636, 423).R(638, 425)));
			files.Add(@"map0R.cpk/mapfile_varoR.cpk/map/sce/R/ja/varo_d02.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_varoR.cpk/map/sce/R/ja/varo_d03.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_varoR.cpk/map/sce/R/ja/varo_d04.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_varoR.cpk/map/sce/R/ja/varo_d05.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_varoR.cpk/map/sce/R/ja/varo_d06.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_varoR.cpk/map/sce/R/ja/varo_d07.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_varoR.cpk/map/sce/R/ja/varo_d08.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_varoR.cpk/map/sce/R/ja/varo_d09.scs", new MappingData(c: true, u: GenerateCommonU(452), j: GenerateCommonJ(452), w: new W().R(639, 428).R(641, 430).R(494, 277)));
			files.Add(@"map0R.cpk/mapfile_varoR.cpk/map/sce/R/ja/varo_d10.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_varoR.cpk/map/sce/R/ja/varo_d11.scs", new MappingData(c: true, u: GenerateCommonU(444), j: GenerateCommonJ(444), w: new W().R(632, 420).R(634, 422)));
			files.Add(@"map0R.cpk/mapfile_varoR.cpk/map/sce/R/ja/varo_d12.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_varoR.cpk/map/sce/R/ja/varo_d13.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_varoR.cpk/map/sce/R/ja/varo_d14.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_varoR.cpk/map/sce/R/ja/varo_d15.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_varoR.cpk/map/sce/R/ja/varo_d16.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_varoR.cpk/map/sce/R/ja/varo_d17.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_varoR.cpk/map/sce/R/ja/varo_d18.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_varoR.cpk/map/sce/R/ja/varo_d19.scs", new MappingData(c: true, u: GenerateCommonU(476), j: GenerateCommonJ(476), w: new W().R(665, 452).R(667, 454)));
			files.Add(@"map0R.cpk/mapfile_varoR.cpk/map/sce/R/ja/varo_d20.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_varoR.cpk/map/sce/R/ja/varo_d21.scs", new MappingData(c: true, u: GenerateCommonU(454), j: GenerateCommonJ(454), w: new W().R(645, 430).R(647, 432).Sys(545).Sys(546)));
			files.Add(@"map0R.cpk/mapfile_varoR.cpk/map/sce/R/ja/varo_d22.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().Sys(558).Sys(559)));
			files.Add(@"map0R.cpk/mapfile_varoR.cpk/map/sce/R/ja/varo_d23.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_varoR.cpk/map/sce/R/ja/varo_d24.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_varoR.cpk/map/sce/R/ja/varo_d25.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_varoR.cpk/map/sce/R/ja/varo_d26.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_varoR.cpk/map/sce/R/ja/varo_d27.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_varoR.cpk/map/sce/R/ja/varo_d28.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_varoR.cpk/map/sce/R/ja/varo_d29.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_varoR.cpk/map/sce/R/ja/varo_d30.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_wf01R.cpk/map/sce/R/ja/e103_010.scs", new MappingData(c: true, u: GenerateDefault().A(272, -4), w: new W().Sys(105)));
			files.Add(@"map0R.cpk/mapfile_wf01R.cpk/map/sce/R/ja/e103_011.scs", new MappingData(c: true, u: GenerateDefault().A(272, -4), w: new W().Sys(105)));
			files.Add(@"map0R.cpk/mapfile_wf01R.cpk/map/sce/R/ja/e103_110.scs", new MappingData(c: true, u: GenerateDefault().A(272, -4), w: new W().Sys(105)));
			files.Add(@"map0R.cpk/mapfile_wf01R.cpk/map/sce/R/ja/e207_060.scs", new MappingData(c: true, u: GenerateDefault().A(272, -4), w: new W().Sys(105)));
			files.Add(@"map0R.cpk/mapfile_wf01R.cpk/map/sce/R/ja/e207_061.scs", new MappingData(c: true, u: GenerateDefault().A(272, -4), w: new W().Sys(105)));
			files.Add(@"map0R.cpk/mapfile_wf01R.cpk/map/sce/R/ja/e210_090.scs", new MappingData(c: true, u: GenerateDefault().A(272, -4), w: new W().Sys(105)));
			files.Add(@"map0R.cpk/mapfile_wf01R.cpk/map/sce/R/ja/e210_120.scs", new MappingData(c: true, u: GenerateDefault().A(267, -4)));
			files.Add(@"map0R.cpk/mapfile_wf01R.cpk/map/sce/R/ja/e210_130.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_wf01R.cpk/map/sce/R/ja/e210_140.scs", new MappingData(c: true, u: GenerateDefault().A(272, -4), w: new W().Sys(105)));
			files.Add(@"map0R.cpk/mapfile_wf01R.cpk/map/sce/R/ja/e210_150.scs", new MappingData(c: true, u: GenerateDefault().A(270, -24)));
			files.Add(@"map0R.cpk/mapfile_wf01R.cpk/map/sce/R/ja/e316_060.scs", new MappingData(c: true, u: GenerateDefault().A(272, -4), w: new W().Sys(105)));
			files.Add(@"map0R.cpk/mapfile_wf01R.cpk/map/sce/R/ja/e835_110.scs", new MappingData(c: true, u: GenerateDefault(), j: new M().A(296, -1)));
			files.Add(@"map0R.cpk/mapfile_wf01R.cpk/map/sce/R/ja/e937_030.scs", new MappingData(c: true, u: GenerateDefault().A(272, -4)));
			files.Add(@"map0R.cpk/mapfile_wf01R.cpk/map/sce/R/ja/e937_031.scs", new MappingData(c: true, u: GenerateDefault().A(272, -4)));
			files.Add(@"map0R.cpk/mapfile_wf01R.cpk/map/sce/R/ja/koya_r01.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().RP(488, 269, (o, r) => r.ReplaceSubstring(211, 6, o, 128, 9).ReplaceSubstring(117, 6, o, 75, 9))));
			files.Add(@"map0R.cpk/mapfile_wf01R.cpk/map/sce/R/ja/port_i01.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_wf01R.cpk/map/sce/R/ja/port_t01.scs", new MappingData(c: true, u: GenerateDefault().A(396, -23), w: new W().R(492, 273).R(501, 289).R(529, 322).R(531, 330).R(563, 370).R(743, 532)));
			files.Add(@"map0R.cpk/mapfile_wf01R.cpk/map/sce/R/ja/s103_001b.scs", new MappingData(c: true, u: GenerateDefault().A(270, -24)));
			files.Add(@"map0R.cpk/mapfile_wf01R.cpk/map/sce/R/ja/s206_001.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_wf01R.cpk/map/sce/R/ja/wind_e01.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_wf01R.cpk/map/sce/R/ja/wind_f01.scs", new MappingData(c: true, u: GenerateCommonU(586).A(356, -4), j: GenerateCommonJ(589).A(362, 344), w: new W().R(755, 562).R(757, 564).R(494, 275).R(529, 317).Sys(105)));
			files.Add(@"map0R.cpk/mapfile_wf02R.cpk/map/sce/R/ja/e104_060.scs", new MappingData(c: true, u: GenerateDefault().A(269, -3), w: new W().R(529, 307)));
			files.Add(@"map0R.cpk/mapfile_wf02R.cpk/map/sce/R/ja/e206_040.scs", new MappingData(c: true, u: GenerateDefault().A(269, -3)));
			files.Add(@"map0R.cpk/mapfile_wf02R.cpk/map/sce/R/ja/koya_r02.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_wf02R.cpk/map/sce/R/ja/s108_001.scs", new MappingData(c: true, u: GenerateDefault().A(269, -3)));
			files.Add(@"map0R.cpk/mapfile_wf02R.cpk/map/sce/R/ja/wind_f02.scs", new MappingData(c: true, u: GenerateCommonU(563).A(306, -1), j: GenerateCommonJ(564), w: new W().R(645, 435).R(747, 539).R(749, 541)));
			files.Add(@"map0R.cpk/mapfile_wf03R.cpk/map/sce/R/ja/e102_030.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_wf03R.cpk/map/sce/R/ja/e418_090.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_wf03R.cpk/map/sce/R/ja/e418_100.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_wf03R.cpk/map/sce/R/ja/e418_101.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_wf03R.cpk/map/sce/R/ja/e418_120.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_wf03R.cpk/map/sce/R/ja/e418_130.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_wf03R.cpk/map/sce/R/ja/koya_r04.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_wf03R.cpk/map/sce/R/ja/port_i02.scs", new MappingData(c: true, u: GenerateDefault(), w: new W().R(486, 267)));
			files.Add(@"map0R.cpk/mapfile_wf03R.cpk/map/sce/R/ja/port_t02.scs", new MappingData(c: true, u: GenerateDefault().A(298, 294).A(380, 379), w: new W().R(691, 517)));
			files.Add(@"map0R.cpk/mapfile_wf03R.cpk/map/sce/R/ja/s103_001c.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_wf03R.cpk/map/sce/R/ja/wind_f03.scs", new MappingData(c: true, u: GenerateCommonU(539), j: GenerateCommonJ(538).A(275, 274), w: new W().R(492, 274).R(755, 515).R(757, 517)));
			files.Add(@"map0R.cpk/mapfile_wf04R.cpk/map/sce/R/ja/e208_020.scs", new MappingData(c: true, u: GenerateDefault().A(305, -9).A(325, 319), j: new M().A(284, 277).A(287, 281).A(296, 293)));
			files.Add(@"map0R.cpk/mapfile_wf04R.cpk/map/sce/R/ja/e208_021.scs", new MappingData(c: true, u: GenerateDefault().A(305, -9).A(325, 319), j: new M().A(284, 277).A(287, 281).A(296, 293)));
			files.Add(@"map0R.cpk/mapfile_wf04R.cpk/map/sce/R/ja/e210_010.scs", new MappingData(c: true, u: GenerateDefault().A(305, -9).A(325, 319), j: new M().A(284, 277).A(287, 281).A(296, 293)));
			files.Add(@"map0R.cpk/mapfile_wf04R.cpk/map/sce/R/ja/e210_050.scs", new MappingData(c: true, u: GenerateDefault().A(305, -9).A(325, 319), j: new M().A(284, 277).A(287, 281).A(296, 293)));
			files.Add(@"map0R.cpk/mapfile_wf04R.cpk/map/sce/R/ja/e418_020.scs", new MappingData(c: true, u: GenerateDefault().A(305, -9).A(325, 319), j: new M().A(284, 277).A(287, 281).A(296, 293)));
			files.Add(@"map0R.cpk/mapfile_wf04R.cpk/map/sce/R/ja/wind_f04.scs", new MappingData(c: true, u: GenerateCommonU(737).A(462, -5).A(521, 515).A(323, -10).A(321, -10), j: GenerateCommonJ(740).A(441, 434).A(444, 438).A(453, 450).A(325, -10).A(323, -10), w: new W().R(790, 609).R(892, 713).R(894, 715)));
			files.Add(@"map0R.cpk/mapfile_wf05R.cpk/map/sce/R/ja/e312_010.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_wf05R.cpk/map/sce/R/ja/e312_020.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_wf05R.cpk/map/sce/R/ja/e312_021.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_wf05R.cpk/map/sce/R/ja/e312_030.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_wf05R.cpk/map/sce/R/ja/e312_040.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_wf05R.cpk/map/sce/R/ja/e315_010.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_wf05R.cpk/map/sce/R/ja/e836_010.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_wf05R.cpk/map/sce/R/ja/koya_r03.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_wf05R.cpk/map/sce/R/ja/wind_e05.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_wf05R.cpk/map/sce/R/ja/wind_f05.scs", new MappingData(c: true, u: GenerateCommonU(645).A(291, -2), j: GenerateCommonJ(646).A(348, 277), w: new W().R(812, 621).R(814, 623).R(495, 276).R(496, 277).R(504, 290).R(710, 517)));
			files.Add(@"map0R.cpk/mapfile_wf06R.cpk/map/sce/R/ja/e312_080.scs", new MappingData(c: true, u: GenerateDefault().A(268, -28).A(280, 278)));
			files.Add(@"map0R.cpk/mapfile_wf06R.cpk/map/sce/R/ja/e312_090.scs", new MappingData(c: true, u: GenerateDefault().A(268, -28).A(280, 278)));
			files.Add(@"map0R.cpk/mapfile_wf06R.cpk/map/sce/R/ja/wind_f06.scs", new MappingData(c: true, u: GenerateCommonU(653).A(391, -22).A(442, 440), j: GenerateCommonJ(675).A(374, 364), w: new W().R(826, 629).R(828, 631).R(724, 525).R(588, 372)));
			files.Add(@"map0R.cpk/mapfile_wf07R.cpk/map/sce/R/ja/s210_001.scs", new MappingData(c: true, u: GenerateDefault().A(297 - 22, 295 - 22, 296 - 22).A(306 - 22, 297 - 22).A(288, -6), j: new M().A(299 - 22, 297 - 22).A(306 - 22, 304 - 22).A(328, -1).A(340, -1)));
			files.Add(@"map0R.cpk/mapfile_wf07R.cpk/map/sce/R/ja/wind_f07.scs", new MappingData(c: true, u: GenerateDefault().A(297, 295, 296).A(306, 297).A(288 + 22, -6), j: new M().A(299, 297).A(306, 304).A(460, -1).A(461 + 11, -1), w: new W().R(641, 437)));
			files.Add(@"map0R.cpk/mapfile_wf21R.cpk/map/sce/R/ja/e628_060.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_wf21R.cpk/map/sce/R/ja/wind_f21.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_wincR.cpk/map/sce/R/ja/e105_020.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_wincR.cpk/map/sce/R/ja/e105_021.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_wincR.cpk/map/sce/R/ja/e105_022.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_wincR.cpk/map/sce/R/ja/e211_030.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_wincR.cpk/map/sce/R/ja/e211_031.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_wincR.cpk/map/sce/R/ja/e835_120.scs", new MappingData(c: true, u: GenerateDefault(), j: new M().A(309, -1)));
			files.Add(@"map0R.cpk/mapfile_wincR.cpk/map/sce/R/ja/e940_010.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_wincR.cpk/map/sce/R/ja/winc_d01.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_wincR.cpk/map/sce/R/ja/winc_d02.scs", new MappingData(c: true, u: GenerateCommonU(483), j: GenerateCommonJ(483), w: new W().R(672, 459).R(674, 461)));
			files.Add(@"map0R.cpk/mapfile_wincR.cpk/map/sce/R/ja/winc_d03.scs", new MappingData(c: true, u: GenerateDefault()));
			files.Add(@"map0R.cpk/mapfile_zoneR.cpk/map/sce/R/ja/s426_003.scs", new MappingData(c: true, u: GenerateDefault(), j: new M().A(312, 31), w: new W().R(569, 351)));
			files.Add(@"map0R.cpk/mapfile_zoneR.cpk/map/sce/R/ja/s426_004.scs", new MappingData(c: true, u: GenerateDefault(), j: new M().A(376, 31)));
			files.Add(@"map0R.cpk/mapfile_zoneR.cpk/map/sce/R/ja/s426_005.scs", new MappingData(c: true, u: GenerateDefault(), j: new M().A(338, 31)));
			files.Add(@"map0R.cpk/mapfile_zoneR.cpk/map/sce/R/ja/s426_006.scs", new MappingData(c: true, u: GenerateDefault(), j: new M().A(351, 31)));
			files.Add(@"map0R.cpk/mapfile_zoneR.cpk/map/sce/R/ja/s426_007.scs", new MappingData(c: true, u: GenerateDefault(), j: new M().A(353, 31)));
			files.Add(@"map0R.cpk/mapfile_zoneR.cpk/map/sce/R/ja/s426_008.scs", new MappingData(c: true, u: GenerateDefault(), j: new M().A(336, 31)));
			files.Add(@"map0R.cpk/mapfile_zoneR.cpk/map/sce/R/ja/s426_009.scs", new MappingData(c: true, u: GenerateDefault(), j: new M().A(341, 31)));
			files.Add(@"map0R.cpk/mapfile_zoneR.cpk/map/sce/R/ja/s426_010.scs", new MappingData(c: true, u: GenerateDefault(), j: new M().A(325, 322).A(340, 31)));
			files.Add(@"map0R.cpk/mapfile_zoneR.cpk/map/sce/R/ja/s426_011.scs", new MappingData(c: true, u: GenerateDefault(), j: new M().A(345, 31), w: new W().R(541, 322)));
			files.Add(@"map0R.cpk/mapfile_zoneR.cpk/map/sce/R/ja/s426_012.scs", new MappingData(c: true, u: GenerateDefault(), j: new M().A(335, 31)));
			files.Add(@"map0R.cpk/mapfile_zoneR.cpk/map/sce/R/ja/s426_013.scs", new MappingData(c: true, u: GenerateDefault(), j: new M().A(398, 31)));
			files.Add(@"map0R.cpk/mapfile_zoneR.cpk/map/sce/R/ja/zone_d01.scs", new MappingData(c: true, u: GenerateDefault().A(324, -4).A(325, -2).A(365, -1), j: new M().A(286, 31).A(385, -1)));
			files.Add(@"map0R.cpk/mapfile_zoneR.cpk/map/sce/R/ja/zone_d01_01.scs", new MappingData(c: true, u: GenerateDefault().A(363, -4).A(364, -2).A(408, -1), j: new M().A(325, 31).A(428, -1)));
			files.Add(@"map0R.cpk/mapfile_zoneR.cpk/map/sce/R/ja/zone_d01_02.scs", new MappingData(c: true, u: GenerateDefault().A(363, -4).A(364, -2).A(408, -1), j: new M().A(325, 31).A(428, -1)));
			files.Add(@"map0R.cpk/mapfile_zoneR.cpk/map/sce/R/ja/zone_d01_03.scs", new MappingData(c: true, u: GenerateDefault().A(363, -4).A(364, -2).A(408, -1), j: new M().A(325, 31).A(428, -1)));
			files.Add(@"map0R.cpk/mapfile_zoneR.cpk/map/sce/R/ja/zone_d01_04.scs", new MappingData(c: true, u: GenerateDefault().A(363, -4).A(364, -2).A(408, -1), j: new M().A(325, 31).A(428, -1)));
			files.Add(@"map0R.cpk/mapfile_zoneR.cpk/map/sce/R/ja/zone_d01_05.scs", new MappingData(c: true, u: GenerateDefault().A(363, -4).A(364, -2).A(408, -1), j: new M().A(325, 31).A(428, -1)));
			files.Add(@"map0R.cpk/mapfile_zoneR.cpk/map/sce/R/ja/zone_d01_06.scs", new MappingData(c: true, u: GenerateDefault().A(363, -4).A(364, -2).A(408, -1), j: new M().A(325, 31).A(428, -1)));
			files.Add(@"map0R.cpk/mapfile_zoneR.cpk/map/sce/R/ja/zone_d01_07.scs", new MappingData(c: true, u: GenerateDefault().A(363, -4).A(364, -2).A(408, -1), j: new M().A(325, 31).A(428, -1)));
			files.Add(@"map0R.cpk/mapfile_zoneR.cpk/map/sce/R/ja/zone_d01_08.scs", new MappingData(c: true, u: GenerateDefault().A(363, -4).A(364, -2).A(408, -1), j: new M().A(325, 31).A(428, -1)));
			files.Add(@"map0R.cpk/mapfile_zoneR.cpk/map/sce/R/ja/zone_d01_09.scs", new MappingData(c: true, u: GenerateDefault().A(363, -4).A(364, -2).A(408, -1), j: new M().A(325, 31).A(428, -1)));
			files.Add(@"map0R.cpk/mapfile_zoneR.cpk/map/sce/R/ja/zone_d01_10.scs", new MappingData(c: true, u: GenerateDefault().A(363, -4).A(364, -2).A(408, -1), j: new M().A(325, 31).A(428, -1)));
			files.Add(@"map0R.cpk/mapfile_zoneR.cpk/map/sce/R/ja/zone_d02.scs", new MappingData(c: true, u: GenerateDefault().A(313, -2).A(321, -1).A(327, -1).A(328, -1).A(333, -3).A(335, -1), j: new M().A(314, 31).A(330, 33).A(338, -2).A(340, 32), w: new W().Sys(541)));
			files.Add(@"map0R.cpk/mapfile_zoneR.cpk/map/sce/R/ja/zone_d03.scs", new MappingData(c: true, u: GenerateDefault()));
		}
	}
}
